### ISSUE TITLE
Reduce number of fields required to configure TNCO address

### ISSUE THREAD

**Issue by dvaccarosenna** [IBM/lmctl#64]
Currently configuration of a TNCO/LM environment can be bloated, like below:
```
lm:
  host: somehost
  port: 443
  protocol: https
  secure: True
  username: jack
  auth_host: someotherhost
  auth_port: 443
```

In many cases we no longer need the `auth_` properties (and if we support client credentials #55 we can move people away from using the UI host). 

In many cases, needing to split the host, port and protocol is unnecessary work for the user. They were traditionally split to provide defaults to any omitted `auth_` values but as stated earlier, we want to move away from using these properties anyway. 

We could reduce the need for host, port and protocol to a single `address` property. Maintain an `auth_address` for environments that intend to use legacy username/password authentication (pre-client credential support).
