### ISSUE TITLE
A deployment location created thru lmctl does not work properly

### ISSUE THREAD

**Issue by bmpotter** [IBM/lmctl#93]
**Describe the bug**
After creating a deployment location via `lmctl create deploymentlocation -e clus108 -f dl-properties-bpfyre6.yaml` (which appeared to succeed), I then used the UI to instantiated an assembly based on it. The intent for that failed with the message that the DL was missing the property `clientConfig`, even though the yaml file above did contain `clientConfig`. (The same process succeeded when creating the DL via the UI.)

**To Reproduce**
Steps to reproduce the behaviour:
1. Create file `dl-properties-bpfyre6.yaml` with content like:
```
id: microk8s-193
name: microk8s-193
description: Running on fyre 9.30.222.193 owned by bp
resourceManager: brent
infrastructureType: Kubernetes
clientConfig: |
  apiVersion: v1
  clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJ...
      server: https://9.30.222.193:16443
    name: microk8s-cluster
  contexts:
  - context:
      cluster: microk8s-cluster
      user: admin
    name: microk8s
  current-context: microk8s
  kind: Config
  preferences: {}
  users:
  - name: admin
    user:
      token: Y0wyREdz...
```
2. Create a deployment location by running: `lmctl create deploymentlocation -e clus108 -f dl-properties-bpfyre6.yaml`
3. In the TNCO UI in the **Recent Assembly Instances** page, click **Create**
4. Select an assembly descriptor and specify the DL created above.
5. The execution of the make active intent will fail with an error like:
```
Error executing lifecycle Create for resourceId 6041688c-058c-4597-9ea1-5a2423629577 resourceName bp-busybox-microk8s-193__busybox (400 BAD REQUEST: [{"localizedMessage": "Deployment location properties missing value for property 'clientConfig' (or: 'client_config')", "status": 400}])[400 BAD REQUEST: [{"localizedMessage": "Deployment location properties missing value for property 'clientConfig' (or: 'client_config')", "status": 400}]]
```

**Expected behaviour**
The execution of the make active intent should succeed. The same process succeeded when creating the DL via the UI, instead of via `lmctl`.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 CP4NA 2.1

**Additional context**
None

**Comment by dvaccarosenna** [comment]
Hi @bmpotter, attributes such as clientConfig, which are driver specific, need to be nested under `infrastructureSpecificProperties`. Something like:

```
id: microk8s-193
name: microk8s-193
description: Running on fyre 9.30.222.193 owned by bp
resourceManager: brent
infrastructureType: Kubernetes
infrastructureSpecificProperties:
  clientConfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJ...
        server: https://9.30.222.193:16443
      name: microk8s-cluster
    contexts:
    - context:
        cluster: microk8s-cluster
        user: admin
      name: microk8s
    current-context: microk8s
    kind: Config
    preferences: {}
    users:
    - name: admin
      user:
        token: Y0wyREdz...
```

Give this a try and let me know if you have any issues with it.
